# Generated by Django 4.2.4 on 2024-01-16 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0002_remove_movie_telegram_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='telegram_link',
            field=models.URLField(default='https://t.me/c/2047954894/4'),
        ),
        migrations.AddField(
            model_name='series',
            name='telegram_link',
            field=models.URLField(default='https://t.me/c/2047954894/4'),
        ),
    ]
