# Generated by Django 4.2.4 on 2024-01-17 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0003_movie_telegram_link_series_telegram_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='PandaDocs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='pandadocs/')),
            ],
        ),
    ]
