# Generated by Django 4.2.4 on 2024-02-03 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0004_pandadocs'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='telegram_private_channel',
            field=models.CharField(default='-1001802351887', max_length=200),
        ),
        migrations.AddField(
            model_name='series',
            name='telegram_private_channel',
            field=models.CharField(default='-1001802351887', max_length=200),
        ),
    ]
